% File generated by Facile version 0.53a
%
tic;
global ode_tot_cputime;
global ode_num_calls;
ode_tot_cputime = 0.0;
ode_num_calls = 0;

% initial values (free nodes only)
G0000 = 1.24960914129199;
TG00000 = 9.99999999999999;
G0000_TG00000i00 = 0;
TG00001 = 0;
G0241 = 5.09031745856789;
G0241_TG00001i00 = 0;
LG0000 = 0.001;
G0000_LG0000i00 = 0;
G0241_LG0000i00 = 0;
if exist('ivalues') == 0
ivalues = [G0000 TG00000 G0000_TG00000i00 TG00001 G0241 G0241_TG00001i00 LG0000 G0000_LG0000i00 ...
	G0241_LG0000i00];
end
% rate constants and constant expressions
fb00             = 1;
bb00             = 0.251188643150958;
kp00             = 0.207355491991768;
fb01             = 1.99526231496888;
bb01             = 1;
kp01             = 0.033946248715068;
clamp_sink_LG0000 = 4.0;
global ode_rate_constants;
ode_rate_constants = [fb00 bb00 kp00 fb01 bb01 kp01 clamp_sink_LG0000];

% time interval
t0= 0;
tf= 20000;

% call solver routine 
global event_times;
global event_flags;
ode_events = [0 0 0];
[t, y, intervals]= G016_I00_ode_event(@ode23s, @G016_I00_odes, [t0:1.0:tf], ivalues, odeset(), ode_events, [500.0], [0.001], [1e-06]);


% map free node state vector names
G0000 = y(:,1); TG00000 = y(:,2); G0000_TG00000i00 = y(:,3); TG00001 = y(:,4); G0241 = y(:,5); G0241_TG00001i00 = y(:,6); LG0000 = y(:,7); G0000_LG0000i00 = y(:,8); G0241_LG0000i00 = y(:,9); 





if (ode_num_calls > 0)
  ode_avg_cputime = ode_tot_cputime/ode_num_calls*1000;
  str = sprintf('ODE STATS: num ode calls=%d, tot time=%f, avg time=%fms', ode_num_calls, ode_tot_cputime, ode_avg_cputime);
  disp (str)
end

% issue done message for calling/wrapper scripts
str = sprintf('Facile driver script done (elapsed time %f)',toc);
disp (str)

