% File generated by Facile version 0.53a
%
function dydt = G017_I00_odes(t, y)

global event_flags;
global event_times

global ode_tot_cputime;
global ode_num_calls;
ode_start_time = cputime;
ode_num_calls = ode_num_calls + 1;
% state vector to node mapping
G0000 = y(1);
TG00000 = y(2);
G0000_TG00000i00 = y(3);
TG00001 = y(4);
G0241 = y(5);
G0241_TG00001i00 = y(6);
LG0000 = y(7);
G0000_LG0000i00 = y(8);
G0241_G0241i00 = y(9);
G0241_LG0000i00 = y(10);

% constants and constant expressions
global ode_rate_constants;
fb00 = ode_rate_constants(1);
bb00 = ode_rate_constants(2);
kp00 = ode_rate_constants(3);
fb01 = ode_rate_constants(4);
bb01 = ode_rate_constants(5);
kp01 = ode_rate_constants(6);
fb02 = ode_rate_constants(7);
clamp_sink_LG0000 = ode_rate_constants(8);



% dynamic rate expressions
clamp_source_LG0000 = (+(event_flags(1) && ~event_flags(2))*min((t-event_times(1))/1, 1)*5*4.0+event_flags(2)*max(1-(t-event_times(2))/1, 0)*5*4.0);

% differential equations for independent species
dydt(size(y,1),1) = 0;
dydt(1)= + bb00*G0000_TG00000i00 + kp00*G0000_TG00000i00 + bb00*G0000_LG0000i00 - fb00*G0000*TG00000 - fb00*G0000*LG0000 ;
dydt(2)= + bb00*G0000_TG00000i00 + kp01*G0241_TG00001i00 - fb00*G0000*TG00000 ;
dydt(3)= + fb00*G0000*TG00000 - bb00*G0000_TG00000i00 - kp00*G0000_TG00000i00 ;
dydt(4)= + kp00*G0000_TG00000i00 + bb01*G0241_TG00001i00 - fb01*G0241*TG00001 ;
dydt(5)= + bb01*G0241_TG00001i00 + kp01*G0241_TG00001i00 + bb00*G0241_G0241i00 + bb00*G0241_G0241i00 + bb01*G0241_LG0000i00 - fb01*G0241*TG00001 - fb02*G0241*G0241 - fb02*G0241*G0241 - fb01*G0241*LG0000 ;
dydt(6)= + fb01*G0241*TG00001 - bb01*G0241_TG00001i00 - kp01*G0241_TG00001i00 ;
dydt(7)= + bb00*G0000_LG0000i00 + bb01*G0241_LG0000i00 + clamp_source_LG0000 - fb00*G0000*LG0000 - fb01*G0241*LG0000 - clamp_sink_LG0000*LG0000 ;
dydt(8)= + fb00*G0000*LG0000 - bb00*G0000_LG0000i00 ;
dydt(9)= + fb02*G0241*G0241 - bb00*G0241_G0241i00 ;
dydt(10)= + fb01*G0241*LG0000 - bb01*G0241_LG0000i00 ;


ode_end_time = cputime;
ode_tot_cputime = ode_tot_cputime + (ode_end_time - ode_start_time);
