% File generated by Facile version 0.53a
%
tic;
global ode_tot_cputime;
global ode_num_calls;
ode_tot_cputime = 0.0;
ode_num_calls = 0;

% initial values (free nodes only)
G0571R = 6.31810021568482;
TG00001 = 0;
G0571R_TG00001i01 = 0;
TG00000 = 19.99999999999999;
G0571R_TG00000i00 = 0;
G0571T = 0;
G0571T_TG00001i01 = 0;
G0571T_TG00000i00 = 0;
G0571R_LG0000i00 = 0;
G0571R_LG0000_TG00001i01 = 0;
G0571R_LG0000_TG00000i00 = 0;
G0571T_LG0000i00 = 0;
G0571T_LG0000_TG00001i01 = 0;
G0571T_LG0000_TG00000i00 = 0;
LG0000 = 0.001;
if exist('ivalues') == 0
ivalues = [G0571R TG00001 G0571R_TG00001i01 TG00000 G0571R_TG00000i00 G0571T G0571T_TG00001i01 G0571T_TG00000i00 ...
	G0571R_LG0000i00 G0571R_LG0000_TG00001i01 G0571R_LG0000_TG00000i00 G0571T_LG0000i00 G0571T_LG0000_TG00001i01 G0571T_LG0000_TG00000i00 LG0000];
end
% rate constants and constant expressions
fb00             = 0.0630957344480194;
bb00             = 3.98107170553497;
kp00             = 0.145956309563553;
bb01             = 7.94328234724282;
kp01             = 0.221840612532554;
fb01             = 1;
bb02             = 0.501187233627272;
kp02             = 0.00109914684711349;
fb02             = 0.501187233627272;
kp03             = 0.227914135254419;
fb03             = 0.251188643150958;
bb03             = 1;
fb04             = 7.94328234724282;
bb04             = 0.251188643150958;
fu00             = 0.0104604493786899;
bu00             = 1.01359650093856;
fu01             = 0.526392718253039;
bu01             = 0.405158200382089;
fu02             = 0.0981712587907966;
bu02             = 0.600204324531248;
fu03             = 0.526392718253038;
fu04             = 4.94019271050495;
bu03             = 0.239915690083236;
fu05             = 26.4892342382834;
bu04             = 0.161951197724984;
clamp_sink_LG0000 = 4.0;
global ode_rate_constants;
ode_rate_constants = [fb00 bb00 kp00 bb01 kp01 fb01 bb02 kp02 fb02 kp03 fb03 bb03 ...
	fb04 bb04 fu00 bu00 fu01 bu01 fu02 bu02 fu03 fu04 bu03 fu05 ...
	bu04 clamp_sink_LG0000];

% time interval
t0= 0;
tf= 20000;

% call solver routine 
global event_times;
global event_flags;
ode_events = [0 0 0];
[t, y, intervals]= G045_I00_ode_event(@ode23s, @G045_I00_odes, [t0:1.0:tf], ivalues, odeset(), ode_events, [500.0], [0.001], [1e-06]);


% map free node state vector names
G0571R = y(:,1); TG00001 = y(:,2); G0571R_TG00001i01 = y(:,3); TG00000 = y(:,4); G0571R_TG00000i00 = y(:,5); G0571T = y(:,6); G0571T_TG00001i01 = y(:,7); G0571T_TG00000i00 = y(:,8); G0571R_LG0000i00 = y(:,9); G0571R_LG0000_TG00001i01 = y(:,10); 
G0571R_LG0000_TG00000i00 = y(:,11); G0571T_LG0000i00 = y(:,12); G0571T_LG0000_TG00001i01 = y(:,13); G0571T_LG0000_TG00000i00 = y(:,14); LG0000 = y(:,15); 





if (ode_num_calls > 0)
  ode_avg_cputime = ode_tot_cputime/ode_num_calls*1000;
  str = sprintf('ODE STATS: num ode calls=%d, tot time=%f, avg time=%fms', ode_num_calls, ode_tot_cputime, ode_avg_cputime);
  disp (str)
end

% issue done message for calling/wrapper scripts
str = sprintf('Facile driver script done (elapsed time %f)',toc);
disp (str)

