% File generated by Facile version 0.53a
%
tic;
global ode_tot_cputime;
global ode_num_calls;
ode_tot_cputime = 0.0;
ode_num_calls = 0;

% initial values (free nodes only)
G0000R = 18.865130945543;
TG00001 = 0;
G0000R_TG00001i01 = 0;
TG00000 = 19.99999999999999;
G0000R_TG00000i00 = 0;
G0000T = 0;
G0000T_TG00001i01 = 0;
G0000T_TG00000i00 = 0;
G0000R_LG0000i00 = 0;
G0000R_LG0000_TG00001i01 = 0;
G0000R_LG0000_TG00000i00 = 0;
G0000T_LG0000i00 = 0;
G0000T_LG0000_TG00001i01 = 0;
G0000T_LG0000_TG00000i00 = 0;
LG0000 = 0.001;
if exist('ivalues') == 0
ivalues = [G0000R TG00001 G0000R_TG00001i01 TG00000 G0000R_TG00000i00 G0000T G0000T_TG00001i01 G0000T_TG00000i00 ...
	G0000R_LG0000i00 G0000R_LG0000_TG00001i01 G0000R_LG0000_TG00000i00 G0000T_LG0000i00 G0000T_LG0000_TG00001i01 G0000T_LG0000_TG00000i00 LG0000];
end
% rate constants and constant expressions
fb00             = 0.125892541179417;
bb00             = 1;
kp00             = 0.0399183903354366;
fb01             = 3.98107170553497;
bb01             = 1.99526231496888;
kp01             = 0.375647115760237;
bb02             = 15.8489319246111;
kp02             = 0.0300611689965592;
fb02             = 0.501187233627272;
kp03             = 0.0018865130945543;
fb03             = 31.6227766016838;
bb03             = 0.125892541179417;
fu00             = 1.21357458052697;
bu00             = 1.364260674966;
fu01             = 105.384356647741;
bu01             = 0.0593754669539658;
fu02             = 0.359192672264773;
bu02             = 3.20743864685577;
fu03             = 0.23937629120475;
bu03             = 4.26493113860807;
fu04             = 31.1915635731007;
bu04             = 0.139594412473997;
fu05             = 20.7869519105952;
bu05             = 0.185618688955961;
clamp_sink_LG0000 = 4.0;
global ode_rate_constants;
ode_rate_constants = [fb00 bb00 kp00 fb01 bb01 kp01 bb02 kp02 fb02 kp03 fb03 bb03 ...
	fu00 bu00 fu01 bu01 fu02 bu02 fu03 bu03 fu04 bu04 fu05 bu05 ...
	clamp_sink_LG0000];

% time interval
t0= 0;
tf= 20000;

% call solver routine 
global event_times;
global event_flags;
ode_events = [0 0 0];
[t, y, intervals]= G058_I00_ode_event(@ode23s, @G058_I00_odes, [t0:1.0:tf], ivalues, odeset(), ode_events, [500.0], [0.001], [1e-06]);


% map free node state vector names
G0000R = y(:,1); TG00001 = y(:,2); G0000R_TG00001i01 = y(:,3); TG00000 = y(:,4); G0000R_TG00000i00 = y(:,5); G0000T = y(:,6); G0000T_TG00001i01 = y(:,7); G0000T_TG00000i00 = y(:,8); G0000R_LG0000i00 = y(:,9); G0000R_LG0000_TG00001i01 = y(:,10); 
G0000R_LG0000_TG00000i00 = y(:,11); G0000T_LG0000i00 = y(:,12); G0000T_LG0000_TG00001i01 = y(:,13); G0000T_LG0000_TG00000i00 = y(:,14); LG0000 = y(:,15); 





if (ode_num_calls > 0)
  ode_avg_cputime = ode_tot_cputime/ode_num_calls*1000;
  str = sprintf('ODE STATS: num ode calls=%d, tot time=%f, avg time=%fms', ode_num_calls, ode_tot_cputime, ode_avg_cputime);
  disp (str)
end

% issue done message for calling/wrapper scripts
str = sprintf('Facile driver script done (elapsed time %f)',toc);
disp (str)

